<?xml version="1.0" encoding="UTF-8"?>
<ActionCollection version="2" name="Scripts">
    <Actions category="Scripts">
        <text>Quick Access Manager</text>

        <Action name="save_preset_xml_data">
            <icon></icon>
            <text>Save Presets XML Data</text>
            <iconText></iconText>
            <activationFlags>1</activationFlags>
            <activationConditions>0</activationConditions>
            <shortcut></shortcut>
            <isCheckable>false</isCheckable>
            <statusTip></statusTip>
        </Action>


    </Actions>
</ActionCollection>